<a href="https://colab.research.google.com/github/monsad/Python_Boto3/blob/master/lekcja2a.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Biblioteki



## [numpy](http://cs231n.github.io/python-numpy-tutorial/)
To biblioteka do pracy z wektorami lub macierzami. Jest bardzo szybka i dlatego będziemy jej używać.

In [0]:
import numpy as np #domyślnie numpy jest nadawy alias "np"

In [0]:
arr = np.array([1, 2, 3, 4, 5, 6]) # tablica
arr

array([1, 2, 3, 4, 5, 6])

In [0]:
type(arr)

numpy.ndarray

In [0]:
np.array([1, 2, 3]) + np.array([5, 6, 7])

array([ 6,  8, 10])

In [0]:
np.mean([1, 2, 3])

2.0

In [0]:
np.array([1, 2, 3]).mean()

2.0

In [0]:
print(arr == 1) #tylko pierwszy element jest True (bo jest równy 1)
print(arr == 2) #tylko drugie element jest True (bo jest równy 2)
print(arr > 2) #pierwsze dwa nie pasują (tylko 3 i wyżej są większe od 2), reszt pasuję
print(arr %2 == 0) # tylko parzyste

[ True False False False False False]
[False  True False False False False]
[False False  True  True  True  True]
[False  True False  True False  True]


Zostawiamy tylko parzyste elementy w tablicy. Operator "%" to jest [modulo](https://pl.wikipedia.org/wiki/Modulo).

In [0]:
arr[ arr % 2 == 0 ]

array([2, 4, 6])

Na samym dole strony są dwa linki do 2-godzinnych webinarów na temat: python/numpy + pandas. Są tam również przykłady na githubie. Zapoznaj się z tym i spróbuj to wykonać samodzielnie (przynajmniej część).

# Zadania domowe


Masz listę od 0 do 18. Twoim zadaniem jest zostawić tylko liczby, które dzielą się na 4 bez reszty (czyli 0, 4, 8, 12 i 16). Nie używaj czystego Pythona, tylko postaraj się wykorzystać nowe biblioteki. 

## [pandas](https://www.dataquest.io/blog/pandas-python-tutorial/)
To biblioteka, która będzie nam bardzo potrzebna dalej. Można zaryzykować stwierdzenie, że to bardziej rozbudowany numpy

In [0]:
import pandas as pd #domyślnie pandas jest nadawy alias "pd"

`Pandas` wewnątrz używa `numpy`, dlatego składnia, np. filtrowania, jest podobna. Bardzo łatwo można także konwertować dane z `pandas` do `numpy`.



In [0]:
np.random.seed(2018)
rows = 15

df = pd.DataFrame({
    'height': np.random.randint(140, 210, rows),
    'weight': np.random.randint(50, 80, rows),
})

df

height  weight
0      149      76
1      161      56
2      168      63
3      160      71
4      146      72
5      165      73
6      165      50
7      187      73
8      165      58
9      200      57
10     171      59
11     162      70
12     146      58
13     182      67
14     140      77

Dostać się do danych w wybranej kolumnie, można na co najmniej dwa sposoby.

In [0]:
df.height

#lub

df['height']

0     149
1     161
2     168
3     160
4     146
5     165
6     165
7     187
8     165
9     200
10    171
11    162
12    146
13    182
14    140
Name: height, dtype: int64



## Filtrowanie
Kolejna operacja, która jest bardzo potrzebna, to filtrowanie. Załóżmy, że chcemy zostawić w tabelce ludzi, którzy mają mniej niż 145 cm lub więcej niż 195 cm.

In [0]:
df[ (df.height < 145) | (df.height > 195) ]

height  weight  count     ratio
9      200      57      1  3.508772
14     140      77      1  1.818182

Zwróć uwagę na składnię.

Po pierwsze, jeśli jest więcej niż jeden filtr, należy pojedyncze wyrażenia trzymać w nawiasach (to jest koniecznie).

Po drugie pomiędzy wyrażeniami logicznymi jest operator, w tym przypadku "lub" czyli pionowa kreska (ang. pipe) "|". 
Również może być operator "i", wtedy należy użyć [ampersandy/etki](https://pl.wikipedia.org/wiki/Et) "&".

Po trzecie, wyrażeń logicznych może być więcej niż jedno, ale powyżej trzech trudno jest to czytać i łatwo popełnić błąd.

In [0]:
if 'ratio' in df: del df['ratio']

## Zadanie 2

Zrób `dataframe`, który na początek zawiera dwie kolumny:
- **age** (losowe wartości od 15 do 50)
- **weight** (losowe wartości od 50 do 80)